main: wbs.chatgame.ChatGame
name: ChatGame
version: 0.1.0
api-version: 1.13
author: Weber588
description: Chat-based games with points and rewards
commands:
  chatgame:
    aliases: [cg]
    description: Interact with the ChatGame
    usage: /chatgame help
  guess:
    aliases: [g]
    description: Guess in the ChatGame
    usage: /guess <guess>
permissions:
  chatgame.*:
    default: op
    description: All permissions associated with the ChatGame plugin.
    children:
      chatgame.admin.*:
        description: All admin permissions
        children:
          chatgame.admin.start:
            description: Ability to start the game
          chatgame.admin.stop:
            description: Ability to stop the game
          chatgame.admin.restart:
            description: Ability to restart the game
          chatgame.admin.reload:
            description: Ability to reload the configs
          chatgame.admin.skip:
            description: Ability to skip the current round
          chatgame.admin.next:
            description: Ability to choose the next game type
          chatgame.admin.custom:
            description: Ability to create custom, one-time trivia questions for the next round
      